server:
  port: 8082
spring:
  application:
    name: notification-service
  main:
    banner-mode: off
  kafka:
    consumer:
      group-id: notification-service-consumer-group
    bootstrap-servers: localhost:9092

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: popug
  ssl-required: external
  resource: notification-service
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
  bearer-only: true
