version: '3'

services:
  keycloak-postgres:
    image: postgres
    container_name: keycloak-postgres
    volumes:
      - ./keycloak-postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_DB_PASSWORD:-keycloak}
    ports:
      - 5433:5432

  keycloak:
     #rmage: jboss/keycloak:latest
     #image: localbuild/keycloak:17.0.0
    image: wizzn/keycloak:14
    container_name: keycloak
    restart: unless-stopped
    domainname: ${DOMAIN:-domain.local}
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      DB_USER: ${KEYCLOA_POSTGRES_DB_USER:-keycloak}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_DB_PASSWORD:-keycloak}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 9080:8080
    depends_on:
      - keycloak-postgres

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

