version: '3'

volumes:
    keycloak-postgres-storage:

services:
  keycloak-postgres:
    image: postgres
    container_name: keycloak-postgres
    volumes:
      - keycloak-postgres-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_DB_PASSWORD:-keycloak}
    ports:
      - 5433:5432

  keycloak:
     #rmage: jboss/keycloak:latest
     #image: localbuild/keycloak:17.0.0
    image: wizzn/keycloak:14
    container_name: keycloak
    restart: unless-stopped
    domainname: ${DOMAIN:-domain.local}
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      DB_USER: ${KEYCLOA_POSTGRES_DB_USER:-keycloak}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_DB_PASSWORD:-keycloak}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - keycloak-postgres


