version: '3'

services:
  popug-storage:
    image: postgres
    container_name: popug-storage
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POPUG_POSTGRES_DB_USER:-popuguser}
      POSTGRES_PASSWORD: ${POPUG_POSTGRES_DB_PASSWORD:-popugpassword}
    ports:
      - "5434:5432"