spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type: trace