version: '3'

services:
  keycloak-postgres:
    image: postgres
    container_name: keycloak-postgres
    volumes:
      - keycloak-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_DB_PASSWORD:-keycloak}
    ports:
      - "5433:5432"

  keycloak:
    image: wizzn/keycloak:14
    container_name: keycloak
    restart: unless-stopped
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    domainname: ${DOMAIN:-domain.local}
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      DB_USER: ${KEYCLOAK_POSTGRES_DB_USER:-keycloak}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_DB_PASSWORD:-keycloak}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./data/realm-export.json:/tmp/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-postgres

volumes:
  keycloak-storage:

